### ISSUE TITLE
Unable to use this gem

### ISSUE THREAD

**Issue by alex-fedorov** [mojolingo/es-reindex#16]
It depends on activesupport (because it tries to use `#present?` on its options, which is not present in normal ruby, at least not in my setup).

Defining this method on Object makes it work until it fails in next place:

```
NoMethodError: undefined method `[]' for nil:NilClass
    from <HOME>/.gems-2.1.5/gems/es-reindex-0.3.0/lib/es-reindex.rb:134:in `get_settings'
    from <HOME>/.gems-2.1.5/gems/es-reindex-0.3.0/lib/es-reindex.rb:107:in `create_destination'
    from <HOME>/.gems-2.1.5/gems/es-reindex-0.3.0/lib/es-reindex.rb:80:in `copy!'
    from <HOME>/.gems-2.1.5/gems/es-reindex-0.3.0/lib/es-reindex.rb:15:in `block in copy!'
    from <HOME>/.gems-2.1.5/gems/es-reindex-0.3.0/lib/es-reindex.rb:13:in `tap'
    from <HOME>/.gems-2.1.5/gems/es-reindex-0.3.0/lib/es-reindex.rb:13:in `copy!'
    from (irb):19
    from /opt/rubies/ruby-2.1.5/bin/irb:11:in `<main>'
```

**Comment by benlangfeld** [comment]
Have you tried adding a dependency on activesupport? Does that resolve all of your issues?

**Comment by alex-fedorov** [comment]
Yes, it doesn't solve last error.

Which versions of elastic this gem was tested against?

**Comment by benlangfeld** [comment]
It's actively used with the following

```
    elasticsearch (1.0.6)
      elasticsearch-api (= 1.0.6)
      elasticsearch-transport (= 1.0.6)
    elasticsearch-api (1.0.6)
      multi_json
    elasticsearch-model (0.1.5)
      activesupport (> 3)
      elasticsearch (> 0.4)
      hashie
    elasticsearch-persistence (0.1.5)
      activemodel (> 3)
      activesupport (> 3)
      elasticsearch (> 0.4)
      elasticsearch-model (>= 0.1)
      hashie
      virtus
    elasticsearch-rails (0.1.4)
    elasticsearch-transport (1.0.6)
      faraday
      multi_json
```

Are you able to run the test suite?

**Comment by alex-fedorov** [comment]
Yes it is green for me. But that is because there is this development dependency:

`s.add_development_dependency 'elasticsearch-persistence', '~> 0.1'`

which depends on activesupport.

Is it really a development dependency?

**Comment by benlangfeld** [comment]
Perhaps you could expand upon how you invoked this, which you don't explain in your original bug report. Perhaps you could also try looking at [the method that's raising](https://github.com/mojolingo/es-reindex/blob/master/lib/es-reindex.rb#L128-L136), maybe place a debugger and check the values of variables there...

**Comment by alex-fedorov** [comment]
I was just running it like that:

```
gem install es-reindex
es-reindex -r $SOURCE_URL/$INDEX $DESTINATION_URL/$INDEX
```

**Comment by alex-fedorov** [comment]
After removing `#present?` and `#try` usage (they are from activesupport), I still had this problem. And turned out it is because it can't handle index name aliases. In this situation:

source has indexes:
- index_a
- index_b -> (alias) -> index_a

and when you run it like

`es-reindex -r $SOURCE_URL/index_b $DEST_URL/index_c`

you will get this error, because there is no key `index_b` on settings of `index_a` index.

**Comment by alex-fedorov** [comment]
And this is actually a problem, because I use aliases during 0-downtime deployment with elastic schema migration, i.e.:
1. Initial state: `index_production => (aliased) => index_a`
2. Deploy code
3. Drop `index_b`
4. Create `index_b` with new schema
5. Run the code to populate `index_b` from `index_a`
6. Atomically change alias to `index_production => (aliased) => index_b`
7. Done

I.e. indexes could be swapped atomically which is great. That is why I can't use this on real index instead of alias, because alias can point to one of the two indexes, and it swaps with each deploy.

Of course it is possible to store this info somewhere each time after deployment, but sounds like to much of a hassle.

So settings returned by alias `index_production` look like:

``` json
{
  "index_b": { ... }
}
```

And that is why mentioned code fails, because it expects that key `index_production` exists. Which is not. But as far as I know there could be only one key or error there in `/_settings` response of elastic api, so should not pose a problem just to get first key available and just use it. WDYT?

**Comment by alex-fedorov** [comment]
@benlangfeld I have found the cause of the problem (see my 2 previous comments). Do you think this should be fixed in the gem, or should I use some sort of workaround for my setup?

**Comment by benlangfeld** [comment]
This should probably be accounted for in the gem, but I'll defer to @JustinAiken and @victorluft to continue from here. Thanks for the details.

**Comment by JustinAiken** [comment]
> Is it really a development dependency?

Oh yeah, it's used in the integration tests [here](https://github.com/mojolingo/es-reindex/blob/master/spec/support/test_model.rb#L1) 

> After removing #present? and #try usage (they are from activesupport)

Ooh, I'll add activesupport as a (non-development) dependency tomorrow; thanks for catching that!

>  Do you think this should be fixed in the gem, or should I use some sort of workaround for my setup?

If you want to submit a PR that keeps the current tests green, I'd be happy to merge :smile:

**Comment by alex-fedorov** [comment]
Ok, I will look into that this weekend

## 

Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-02-14 0:57 GMT+02:00 Justin Aiken notifications@github.com:

**Comment by JustinAiken** [comment]
I just pushed [0.3.1](https://github.com/mojolingo/es-reindex/releases/tag/0.3.1) with the activesupport dependency.

**Comment by alex-fedorov** [comment]
I still think that this dependency is unnecessary, because its monkey patching can conflict with other libraries one could use. And monkey patching overall is bad, especially in small utility gems. By the way `#try` and `#present?` are not hard to do with pure ruby:

``` ruby
# x.try(:hello)
x && x.hello
```

``` ruby
# if some_hash[:some_key].present?
if some_hash.has_key?(:some_key)
  # ...
end
```

By the way `#try` is not the best thing in the world, since it can raise exception when called on non-nil object and it is not responding to specified method. Even worse: this behaviour changes from 3 to 4 version of active support.

And the last argument against active support: What if I don't use rails and active support at all? Why do I want to load such a huge dependency?

**Comment by benlangfeld** [comment]
Justin did the fastest thing he could to fix the problem you reported. He has a lot of other things to do also. If you think ActiveSupport should be removed, go ahead and submit a pull request that does so.

**Comment by alex-fedorov** [comment]
@benlangfeld I actually want to submit such PR, but I wanted to make sure, that nobody is opposed to that. Could be that I don't see a full picture

**Comment by waterlink** [comment]
@JustinAiken @benlangfeld Any news on this one: #18

**Comment by JustinAiken** [comment]
Sorry for the delay, but both your changes work beautifully; just pushed out 0.3.2 with them in.

**Comment by waterlink** [comment]
Thx!

## 

Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-02-27 18:05 GMT+02:00 Justin Aiken notifications@github.com:
