### ISSUE TITLE
Can't make it run

### ISSUE THREAD

**Issue by syunusic** [mojolingo/es-reindex#22]
Probably is a ultra simple problem, but I'm not a ruby expert, sorry.
I have ruby 2.0, with gem elasticsearch installed. When I go to es-reindex/bin, I executed the binary and this is what happen:

```
$ ./es-reindex
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require': cannot load such file -- es-reindex (LoadError)
        from /usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
        from ./es-reindex:3:in `<main>'

```

What is missing? Should I move the folder somewhere else?

**Comment by benlangfeld** [comment]
Did you install the gem or check out the repository. If you installed the gem, es-reindex should be in your path. 

Enviado do meu iPhone

**Comment by syunusic** [comment]
As I told you, I'm not an expert.. 
$ sudo gem2.0 install es-reindex
That did the trick. Even is really basic, shouldn't be a bad idea to put that in the README.
